backend:
  name: github
  repo: juliosilvar/jjuliosilvar-homenaje
  branch: main
  auth_type: oauth
  app_id: Ov23lijhpS2Dqp1NBhUr

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "pagina"
    label: "Página Homenaje"
    folder: "content/pagina"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }
